[package]
name = "px-rocket-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "1.1.0", features = ["full"] }
hyper-util = { version = "0.1.2", features = ["full"] }
tokio = { version = "1.35.1", features = ["full"] }
http-body-util = "0.1.0"
bytes = "1.5.0"